### ISSUE TITLE
一緒に勉強出来れば良いなと

### ISSUE THREAD

**Issue by sekaininagaja** [emmr/study_Python#1]
@emmr 　
pythonの勉強したくて色々検索したら
emmr様がいい資料を。。感謝します。
邪魔になると思いますが、色々勉強させてください。
githubの使い方が良く分からないので変なのやるかもしれませんが
宜しくお願いします。

**Comment by emmr** [comment]
@sekaininagaja 
はじめまして。こちらこそ一緒に勉強できたらうれしいです。
WEB資料を機械翻訳しつつ自分のために書きなぐったものですが、参考になれば幸いです。

**Comment by sekaininagaja** [comment]
@emmr

**Comment by sekaininagaja** [comment]
@emmr 
そうですね。
最近時間がなくてあまり見れてないのですが、ありがとうございます。
時間ある時また見てみようと思っていますので、宜しくお願いします。
githubの使い方が良く分からないので＾＾「closed」？？
